### ISSUE TITLE
对高版本插件模组杂交端的支持

### ISSUE THREAD

**Issue by hu7x** [R-Josef/BBSToper#12]
测试服务端:[Loliserver-1.16.5](https://github.com/Loli-Server/LoliServer1.16)
使用主指令/bt时的输出:
[15:50:53][WARN/]: [BBSToper] Plugin BBSToper v3.6.2 generated an exception while executing task 153
 java.lang.NoSuchFieldError: STAINED_GLASS_PANE
        at moe.feo.bbstoper.gui.GUI.getRandomPane(GUI.java:144) ~[?:?]
        at moe.feo.bbstoper.gui.GUI.createGui(GUI.java:54) ~[?:?]
        at moe.feo.bbstoper.gui.GUI.<init>(GUI.java:36) ~[?:?]
        at moe.feo.bbstoper.CLI$1.task(CLI.java:96) ~[?:?]
        at moe.feo.bbstoper.CLI$1.run(CLI.java:88) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [forge:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
或许自定义GUI可以拯救一下？

**Comment by R-Josef** [comment]
我在最新的提交 c23e166 中修复了这个问题，你可以下载最新[release](https://github.com/R-Josef/BBSToper/releases)。我先关闭这个issue了，如果问题没解决的话你可以再在这里回复。
