### ISSUE TITLE
1.16.5使用报错

### ISSUE THREAD

**Issue by HYDeath** [R-Josef/BBSToper#16]
核心：Paper-788
刚启动就报错

[21:33:09 ERROR]: Could not load 'plugins/BBSToper-3.6.7.jar' in folder 'plugins'
>org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:188) ~[patched_1.16.5.jar:git-Paper-788]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:160) ~[patched_1.16.5.jar:git-Paper-788]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-788]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-788]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-788]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-788]
at java.lang.Thread.run(Thread.java:853) [?:1.8.0_302]
>Caused by: org.yaml.snakeyaml.error.YAMLException: java.util.zip.ZipException: invalid LOC header (bad signature)
at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218) ~[patched_1.16.5.jar:git-Paper-788]
at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176) ~[patched_1.16.5.jar:git-Paper-788]
at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171) ~[patched_1.16.5.jar:git-Paper-788]
at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126) ~[patched_1.16.5.jar:git-Paper-788]
at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1177) ~[patched_1.16.5.jar:git-Paper-788]
at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:287) ~[patched_1.16.5.jar:git-Paper-788]
at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[patched_1.16.5.jar:git-Paper-788]
at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195) ~[patched_1.16.5.jar:git-Paper-788]
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.16.5.jar:git-Paper-788]
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.16.5.jar:git-Paper-788]
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:118) ~[patched_1.16.5.jar:git-Paper-788]
at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150) ~[patched_1.16.5.jar:git-Paper-788]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[patched_1.16.5.jar:git-Paper-788]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:429) ~[patched_1.16.5.jar:git-Paper-788]
at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:259) ~[patched_1.16.5.jar:git-Paper-788]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:183) ~[patched_1.16.5.jar:git-Paper-788]
... 6 more

**Comment by HYDeath** [comment]
> 核心：Paper-788 刚启动就报错
> 
> [21:33:09 ERROR]: Could not load 'plugins/BBSToper-3.6.7.jar' in folder 'plugins'
> 
> > org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
> > at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:188) ~[patched_1.16.5.jar:git-Paper-788]
> > at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:160) ~[patched_1.16.5.jar:git-Paper-788]
> > at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-788]
> > at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-788]
> > at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-788]
> > at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-788]
> > at java.lang.Thread.run(Thread.java:853) [?:1.8.0_302]
> > Caused by: org.yaml.snakeyaml.error.YAMLException: java.util.zip.ZipException: invalid LOC header (bad signature)
> > at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:218) ~[patched_1.16.5.jar:git-Paper-788]
> > at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:176) ~[patched_1.16.5.jar:git-Paper-788]
> > at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:171) ~[patched_1.16.5.jar:git-Paper-788]
> > at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:126) ~[patched_1.16.5.jar:git-Paper-788]
> > at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1177) ~[patched_1.16.5.jar:git-Paper-788]
> > at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:287) ~[patched_1.16.5.jar:git-Paper-788]
> > at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[patched_1.16.5.jar:git-Paper-788]
> > at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:195) ~[patched_1.16.5.jar:git-Paper-788]
> > at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.16.5.jar:git-Paper-788]
> > at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.16.5.jar:git-Paper-788]
> > at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:118) ~[patched_1.16.5.jar:git-Paper-788]
> > at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150) ~[patched_1.16.5.jar:git-Paper-788]
> > at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[patched_1.16.5.jar:git-Paper-788]
> > at org.yaml.snakeyaml.Yaml.load(Yaml.java:429) ~[patched_1.16.5.jar:git-Paper-788]
> > at org.bukkit.plugin.PluginDescriptionFile.(PluginDescriptionFile.java:259) ~[patched_1.16.5.jar:git-Paper-788]
> > at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:183) ~[patched_1.16.5.jar:git-Paper-788]
> > ... 6 more

log:
https://paste.ubuntu.com/p/9mnQPg8w7T/

**Comment by HYDeath** [comment]
log:https://paste.ubuntu.com/p/9mnQPg8w7T/

**Comment by R-Josef** [comment]
请问是windows系统吗？

**Comment by HYDeath** [comment]
> 请问是windows系统吗？

Linux CentOS7

**Comment by R-Josef** [comment]
我刚刚在Win10和Debian10上进行了测试，没有复现问题。我怀疑是因为插件.jar文件中的plugin.yml文件的换行符是windows的cr+lf，而不是linux的lf，可能有些系统上不能正常读取，建议你更改plugin.yml文件的换行符试试。

**Comment by HYDeath** [comment]
> 我刚刚在Win10和Debian10上进行了测试，没有复现问题。我怀疑是因为插件.jar文件中的plugin.yml文件的换行符是windows的cr+lf，而不是linux的lf，可能有些系统上不能正常读取，建议你更改plugin.yml文件的换行符试试。

好了，我重新下载新的插件.jar，重新放进去已成功加载了

**Comment by R-Josef** [comment]
好的，那我先关闭issue了，如果有问题的话你可以再留言。
