### ISSUE TITLE
插件报错

### ISSUE THREAD

**Issue by NeglectDream** [R-Josef/BBSToper#24]
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: java.text.ParseException: Unparseable date: ""
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: 	at java.text.DateFormat.parse(DateFormat.java:366)
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: 	at mc233.fun.kbbstoper.Reward.award(Reward.java:122)
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: 	at mc233.fun.kbbstoper.Crawler.activeReward(Crawler.java:134)
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: 	at mc233.fun.kbbstoper.Util$1.task(Util.java:44)
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: 	at mc233.fun.kbbstoper.Util$1.run(Util.java:36)
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: java.text.ParseException: Unparseable date: ""
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: 	at java.text.DateFormat.parse(DateFormat.java:366)
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: 	at mc233.fun.kbbstoper.Reward.isIntervalTooShort(Reward.java:91)
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: 	at mc233.fun.kbbstoper.Reward.award(Reward.java:128)
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: 	at mc233.fun.kbbstoper.Crawler.activeReward(Crawler.java:134)
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: 	at mc233.fun.kbbstoper.Util$1.task(Util.java:44)
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: 	at mc233.fun.kbbstoper.Util$1.run(Util.java:36)
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[01:55:34] [Craft Scheduler Thread - 22988/WARN]: [KBBSToper] Plugin KBBSToper v3.7.1 generated an exception while executing task 105
java.lang.NullPointerException: null
	at mc233.fun.kbbstoper.Reward.isIntervalTooShort(Reward.java:96) ~[?:?]
	at mc233.fun.kbbstoper.Reward.award(Reward.java:128) ~[?:?]
	at mc233.fun.kbbstoper.Crawler.activeReward(Crawler.java:134) ~[?:?]
	at mc233.fun.kbbstoper.Util$1.task(Util.java:44) ~[?:?]
	at mc233.fun.kbbstoper.Util$1.run(Util.java:36) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[%5b2%5dPpaer-1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[%5b2%5dPpaer-1.12.2.jar:git-Paper-1620]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[%5b2%5dPpaer-1.12.2.jar:git-Paper-1620]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_282]
	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_282]

**Comment by R-Josef** [comment]
KBBSToper相关问题请去：https://github.com/SnowCherryServer/KBBSToper

这是BBSToper
