### ISSUE TITLE
它似乎并不支持MySQL8.0

### ISSUE THREAD

**Issue by FortyTwoCn** [R-Josef/BBSToper#25]
```
[19:56:21] [Craft Scheduler Thread - 207/WARN]: java.sql.SQLException: database connection closed
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at org.sqlite.SQLiteConnection.checkOpen(SQLiteConnection.java:390)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:32)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at mc233.fun.kbbstoper.sql.SQLer.checkTopstate(SQLer.java:164)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at mc233.fun.kbbstoper.Crawler.activeReward(Crawler.java:111)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at mc233.fun.kbbstoper.Util$1.task(Util.java:44)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at mc233.fun.kbbstoper.Util$1.run(Util.java:36)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:
54)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at java.lang.Thread.run(Thread.java:855)
[19:56:21] [Craft Scheduler Thread - 207/WARN]: java.sql.SQLException: database connection closed
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at org.sqlite.SQLiteConnection.checkOpen(SQLiteConnection.java:390)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:32)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at mc233.fun.kbbstoper.sql.SQLer.checkTopstate(SQLer.java:164)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at mc233.fun.kbbstoper.Crawler.activeReward(Crawler.java:111)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at mc233.fun.kbbstoper.Util$1.task(Util.java:44)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at mc233.fun.kbbstoper.Util$1.run(Util.java:36)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:
54)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[19:56:21] [Craft Scheduler Thread - 207/WARN]:         at java.lang.Thread.run(Thread.java:855)
```

**Comment by R-Josef** [comment]
KBBSToper相关问题请去：https://github.com/SnowCherryServer/KBBSToper

这是BBSToper
